### ISSUE TITLE
"Rune" ball is present

### ISSUE THREAD

**Issue by pegalink** [Bxelz/eurodex#1]
There's Rune ball, which isn't in Europe. Image below.
![image](https://github.com/user-attachments/assets/e5bb7d61-2f37-49af-81f6-4551304a83e8)

**Comment by pegalink** [comment]
![image](https://github.com/user-attachments/assets/8e2fcea5-d6e3-40cf-83fd-27664a3ed746)
I think at bare minimum it should show only to the developers or in developers collection. Not to everyone. Some people *may* then wonder why they can't get that ball, thus never getting all the balls

**Comment by Bxelz** [comment]
Yeah you make a good point.

**Comment by pegalink** [comment]
This has been now fixed. Closing
